jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your app
        uses: actions/checkout@v3

      - name: Install west and Zephyr dependencies
        run: |
          pip install west
          west init zephyrproject
          cd zephyrproject
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Link your app into workspace
        run: |
          cd zephyrproject
          ln -s $GITHUB_WORKSPACE app

      - name: Build the application
        run: |
          cd zephyrproject
          west build -b nucleo_h745zi_q app
